create table if not exists public."user" (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(100) not null unique,
    password varchar(200) not null,
    is_admin boolean default false
);

create table if not exists public.vehicle (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    "type" varchar(20) not null,
    model varchar(100) not null,
    year integer not null,
    price_per_day double precision not null,
    image_url varchar(200) not null,
    is_available boolean default true,
    description text
);

create table if not exists public.booking (
    id integer generated by default as identity primary key,
    user_id integer not null references public."user"(id) on delete cascade,
    vehicle_id integer not null references public.vehicle(id) on delete cascade,
    start_date timestamp without time zone not null,
    end_date timestamp without time zone not null,
    total_price double precision not null,
    status varchar(20) default 'pending',
    created_at timestamp without time zone default now()
);

insert into public."user" (id, name, email, password, is_admin)
values
    (1, 'Admin User', 'admin@example.com', 'admin123', true),
    (2, 'John Doe', 'user@example.com', 'user123', false)
on conflict (email) do nothing;

insert into public.vehicle (id, name, "type", model, year, price_per_day, image_url, is_available, description)
values
    (1, 'Toyota Camry', 'car', 'Camry SE', 2022, 60.0, 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?ixlib=rb-4.0.3', true, 'A comfortable sedan perfect for family trips. Features include GPS, Bluetooth, and backup camera.'),
    (2, 'Honda Civic', 'car', 'Civic LX', 2021, 50.0, 'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?ixlib=rb-4.0.3', true, 'Fuel-efficient compact car with modern features. Includes Apple CarPlay, Android Auto, and lane assist.'),
    (3, 'Yamaha MT-07', 'bike', 'MT-07', 2023, 40.0, 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?ixlib=rb-4.0.3', true, 'Powerful middleweight motorcycle with excellent handling. Perfect for city rides and weekend trips.'),
    (4, 'BMW R 1250 GS', 'bike', 'R 1250 GS Adventure', 2022, 80.0, 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?ixlib=rb-4.0.3', true, 'Premium adventure motorcycle for long-distance touring. Features include heated grips, cruise control, and multiple riding modes.'),
    (5, 'Ford Mustang', 'car', 'Mustang GT', 2023, 90.0, 'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?ixlib=rb-4.0.3', true, 'Iconic American muscle car with a powerful V8 engine. Includes premium sound system and leather seats.'),
    (6, 'Ducati Panigale V4', 'bike', 'Panigale V4 S', 2023, 100.0, 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?ixlib=rb-4.0.3', true, 'High-performance superbike with cutting-edge technology. Features include electronic suspension, quick shifter, and traction control.')
on conflict (id) do nothing;

insert into public.booking (id, user_id, vehicle_id, start_date, end_date, total_price, status, created_at)
values
    (1, 2, 1, now() + interval '1 day', now() + interval '4 day', 180.0, 'confirmed', now()),
    (2, 2, 3, now() + interval '10 day', now() + interval '12 day', 80.0, 'pending', now())
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public."user"', 'id'), greatest((select coalesce(max(id), 1) from public."user"), 1), true);
select setval(pg_get_serial_sequence('public.vehicle', 'id'), greatest((select coalesce(max(id), 1) from public.vehicle), 1), true);
select setval(pg_get_serial_sequence('public.booking', 'id'), greatest((select coalesce(max(id), 1) from public.booking), 1), true);